### PR TITLE
Quick patch initial support for python 3 and earlier

### PR DESCRIPTION
**Pull request by Ousret**
👋 This is a quick patch. Intended only for reviving this project.

Thank you, 🙏  @vikramarsid for this project. 

This patch will allow you to get started with msg_parser and python 3. Expect bugs PERIOD.
This patch work for me through my basics usages.

As expected, most critical errors are about bytes-like objects vs str objects. 
This patch break compatibility with python 2.7, don't bother trying to support it as it will reach EOL in a month.

Enjoy.

### CODE REVIEW

**Comment by Ousret** [comment]
Linked #50

**Comment by Ousret** [comment]
Tests fixed ! 🎉

**Comment by Ousret** [comment]
ping @vikramarsid 😊

**Comment by vikramarsid** [comment]
@Ousret Thank you so much for starting on Python 3. I have have some updates, I push this holiday season. Thanks again!!

**Pull request merged**
